core = 7.x  
api = 2
projects[drupal][version] = 7.x
  
; Modules
projects[admin_menu][subdir] = "contrib"
projects[advanced_link][subdir] = "contrib"
projects[backup_migrate][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[captcha][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[diff][subdir] = "contrib"
projects[email][subdir] = "contrib"
projects[emptyparagraphkiller][subdir] = "contrib"
projects[entity][subdir] = "contrib"
projects[entity_view_mode][subdir] = "contrib"

projects[epsacrop][subdir] = "contrib"
projects[epsacrop][version] = "2.x-dev"
projects[epsacrop][patch][] = https://drupal.org/files/issues/epsacrop-requirements-block-installation-2237127-1.patch

projects[features][subdir] = "contrib"
projects[fences][subdir] = "contrib"
projects[field_collection][subdir] = "contrib"
projects[field_collection_fieldset][subdir] = "contrib"
projects[field_group][subdir] = "contrib"
projects[google_analytics][subdir] = "contrib"
projects[imageapi][subdir] = "contrib"
projects[imce][subdir] = "contrib"
projects[jquery_update][subdir] = "contrib"
projects[libraries][subdir] = "contrib"
projects[library_pack][subdir] = "contrib"
projects[link][subdir] = "contrib"
projects[module_filter][subdir] = "contrib"
projects[menu_block][subdir] = "contrib"
projects[node_page_disable][subdir] = "contrib"
projects[panels][subdir] = "contrib"
projects[panelizer][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[prod_check][subdir] = "contrib"
projects[recaptcha][subdir] = "contrib"
projects[search404][subdir] = "contrib"
projects[search_krumo][subdir] = "contrib"
projects[security_review][subdir] = "contrib"
projects[site_map][subdir] = "contrib"
projects[strongarm][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[username_enumeration_prevention][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[webform][subdir] = "contrib"
projects[xmlsitemap][subdir] = "contrib"

; Themes
projects[bootstrap][version] = "3.0"
